import React, { useEffect, useRef, useState, useCallback } from 'react';
import { getMermaid } from '../../lib/mermaid-loader.js';

interface MermaidEditorProps {
  code: string;
  onChange: (newCode: string) => void;
}

let renderCounter = 0;

/**
 * Split panel: textarea (mermaid code) + live preview.
 * Design §Mermaid integration, REQ-7.
 */
export function MermaidEditor({ code, onChange }: MermaidEditorProps): React.ReactElement {
  const [previewSvg, setPreviewSvg] = useState<string>('');
  const [previewError, setPreviewError] = useState<string | null>(null);
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const renderPreview = useCallback(async (mermaidCode: string) => {
    if (!mermaidCode.trim()) {
      setPreviewSvg('');
      setPreviewError(null);
      return;
    }
    try {
      const mermaid = await getMermaid();
      const id = `mermaid-preview-${++renderCounter}`;
      const { svg } = await mermaid.render(id, mermaidCode);
      setPreviewSvg(svg);
      setPreviewError(null);
    } catch (err) {
      // Keep previous SVG; show error message below
      setPreviewError(err instanceof Error ? err.message : 'Error de sintaxis Mermaid');
    }
  }, []);

  // Initial render
  useEffect(() => {
    void renderPreview(code);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>): void => {
    const newCode = e.target.value;
    onChange(newCode);

    // Debounce preview update 300ms
    if (timerRef.current) clearTimeout(timerRef.current);
    timerRef.current = setTimeout(() => {
      void renderPreview(newCode);
    }, 300);
  };

  return (
    <div className="mermaid-editor">
      <div className="mermaid-editor-left">
        <textarea
          className="mermaid-textarea"
          value={code}
          onChange={handleChange}
          spellCheck={false}
          placeholder="Código Mermaid..."
        />
      </div>
      <div className="mermaid-editor-right">
        {previewSvg && (
          <div
            className="mermaid-preview"
            // Safe: SVG is generated by mermaid library from user input in local app
            // eslint-disable-next-line react/no-danger
            dangerouslySetInnerHTML={{ __html: previewSvg }}
          />
        )}
        {!previewSvg && !previewError && (
          <div className="mermaid-placeholder">Preview aparecerá aquí</div>
        )}
        {previewError && <div className="mermaid-error">{previewError}</div>}
      </div>
    </div>
  );
}
